version: "2"
services:
  workspace_development:
    build:
      dockerfile: Dockerfile
      args:
        USERNAME: ${username}
        USER_UID: ${user_uid}
        USER_GID: ${user_gid}
        PASSWD: ${passwd}
        DOCKER_GID: ${docker_gid}
    image: ${username}_dev
    environment:
      DISPLAY:
    # container_name: mycontainername
    hostname: dev-host-${username}
    working_dir: /home/${username}/app
    ports:
      - ${host_port}:${container_port}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - ../${project_name}:/home/${username}/app
      - ../${project_name}/.vscode/.vscode-server:/home/${username}/.vscode-server
    command: /bin/sh -c "while sleep 1000; do :; done"
